#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on October 19, 2022 at 14:23:34.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[9];
extern c_float ldata[9];
extern c_float udata[9];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[9];
extern c_float Dinvscaling[9];
extern c_float Escaling[9];
extern c_float Einvscaling[9];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[18];
extern c_int linsys_solver_P[18];
extern c_float linsys_solver_bp[18];
extern c_float linsys_solver_sol[18];
extern c_float linsys_solver_rho_inv_vec[9];
extern c_int linsys_solver_Pdiag_idx[9];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[9];
extern c_int linsys_solver_AtoKKT[25];
extern c_int linsys_solver_rhotoKKT[9];
extern QDLDL_float linsys_solver_D[18];
extern QDLDL_int linsys_solver_etree[18];
extern QDLDL_int linsys_solver_Lnz[18];
extern QDLDL_int   linsys_solver_iwork[54];
extern QDLDL_bool  linsys_solver_bwork[18];
extern QDLDL_float linsys_solver_fwork[18];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[9];
extern c_float ysolution[9];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[9];
extern c_float work_rho_inv_vec[9];
extern c_int work_constr_type[9];
extern c_float work_x[9];
extern c_float work_y[9];
extern c_float work_z[9];
extern c_float work_xz_tilde[18];
extern c_float work_x_prev[9];
extern c_float work_z_prev[9];
extern c_float work_Ax[9];
extern c_float work_Px[9];
extern c_float work_Aty[9];
extern c_float work_delta_y[9];
extern c_float work_Atdelta_y[9];
extern c_float work_delta_x[9];
extern c_float work_Pdelta_x[9];
extern c_float work_Adelta_x[9];
extern c_float work_D_temp[9];
extern c_float work_D_temp_A[9];
extern c_float work_E_temp[9];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
