/*
 * This file was autogenerated by OSQP-Python on January 24, 2023 at 16:52:49.
 * 
 * This file contains the workspace variables needed by OSQP.
 */

#include "types.h"
#include "qdldl_interface.h"

// Define data structure
static c_int Pdata_p[10] = {
0,
1,
2,
3,
4,
5,
6,
7,
8,
9,
};
static c_int Pdata_i[9] = {
0,
1,
2,
3,
4,
5,
6,
7,
8,
};
static c_float Pdata_x[9] = {
(c_float)0.11496861244164006954,
(c_float)0.09503307119900471223,
(c_float)0.08695652173913044625,
(c_float)1.00000000000000022204,
(c_float)1.00000000000000022204,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000022204,
(c_float)1.00000000000000022204,
(c_float)1.00000000000000022204,
};
static csc Pdata = {9, 9, 9, Pdata_p, Pdata_i, Pdata_x, -1};
static c_int Adata_p[10] = {
0,
4,
8,
12,
16,
20,
24,
25,
26,
27,
};
static c_int Adata_i[27] = {
0,
1,
2,
3,
0,
1,
2,
4,
0,
1,
2,
5,
0,
1,
2,
3,
0,
1,
2,
4,
0,
1,
2,
5,
0,
1,
2,
};
static c_float Adata_x[27] = {
(c_float)-0.99962078334930670742,
(c_float)0.99986352304197678720,
(c_float)-0.95759395241855038705,
(c_float)0.33884077807714446662,
(c_float)-0.99971382873076597431,
(c_float)0.99995659101781164679,
(c_float)-0.95768308591404205377,
(c_float)0.30827434404926534750,
(c_float)-0.86935411058646383520,
(c_float)1.00000000000000022204,
(c_float)-0.99936486236529331606,
(c_float)0.29480107939993432931,
(c_float)-0.29481232250918865123,
(c_float)0.29488391230979432711,
(c_float)-0.28241759458758275425,
(c_float)0.99932332750265073784,
(c_float)-0.58962464501837719144,
(c_float)0.58976782461958865422,
(c_float)-0.56483518917516550850,
(c_float)1.00000000000000022204,
(c_float)0.58962464501837719144,
(c_float)0.29488391230979432711,
(c_float)-0.84725278376274792969,
(c_float)0.99971909993593410793,
(c_float)-0.29481232250918865123,
(c_float)-0.14744195615489716356,
(c_float)-0.28241759458758275425,
};
static csc Adata = {27, 6, 9, Adata_p, Adata_i, Adata_x, -1};
static c_float qdata[9] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
};
static c_float ldata[6] = {
(c_float)4.16927584847205512375,
(c_float)2.29365855462782253227,
(c_float)4.79278551022254983849,
(c_float)9.89279622065041230883,
(c_float)11.31370849898476116380,
(c_float)12.72434678723539214218,
};
static c_float udata[6] = {
(c_float)4.16927584847205512375,
(c_float)2.29365855462782253227,
(c_float)4.79278551022254983849,
(c_float)9.89279622065041230883,
(c_float)11.31370849898476116380,
(c_float)12.72434678723539214218,
};
static OSQPData data = {9, 6, &Pdata, &Adata, qdata, ldata, udata};

// Define settings structure
static OSQPSettings settings = {(c_float)0.10000000000000000555, (c_float)0.00000100000000000000, 10, 1, 25, (c_float)5.00000000000000000000, 4000, (c_float)0.00100000000000000002, (c_float)0.00100000000000000002, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)1.00000000000000000000, (enum linsys_solver_type) LINSYS_SOLVER, 0, 25, 1, };

// Define scaling structure
static c_float Dscaling[9] = {
(c_float)0.23975885014076128710,
(c_float)0.21798287914307026836,
(c_float)0.20851441405707477061,
(c_float)0.70710678118654757274,
(c_float)0.70710678118654757274,
(c_float)0.70710678118654757274,
(c_float)0.70710678118654757274,
(c_float)0.70710678118654757274,
(c_float)0.70710678118654757274,
};
static c_float Dinvscaling[9] = {
(c_float)4.17085750708641089801,
(c_float)4.58751624866677154557,
(c_float)4.79583152331271911351,
(c_float)1.41421356237309492343,
(c_float)1.41421356237309492343,
(c_float)1.41421356237309492343,
(c_float)1.41421356237309492343,
(c_float)1.41421356237309492343,
(c_float)1.41421356237309492343,
};
static c_float Escaling[6] = {
(c_float)0.41692758484720549017,
(c_float)0.20851441405707477061,
(c_float)0.39939879251854581987,
(c_float)1.41325660295005883782,
(c_float)1.41421356237309514547,
(c_float)1.41381630969282134913,
};
static c_float Einvscaling[6] = {
(c_float)2.39849805180551278738,
(c_float)4.79583152331271911351,
(c_float)2.50376320292346798979,
(c_float)0.70758558489136436087,
(c_float)0.70710678118654746172,
(c_float)0.70730546333651300728,
};
static OSQPScaling scaling = {(c_float)1.00000000000000000000, Dscaling, Escaling, (c_float)1.00000000000000000000, Dinvscaling, Einvscaling};

// Define linsys_solver structure
static c_int linsys_solver_L_p[16] = {
0,
2,
4,
5,
6,
7,
9,
13,
16,
20,
23,
27,
30,
32,
33,
33,
};
static c_int linsys_solver_L_i[33] = {
10,
11,
8,
9,
14,
12,
13,
6,
7,
7,
12,
13,
14,
12,
13,
14,
9,
12,
13,
14,
12,
13,
14,
11,
12,
13,
14,
12,
13,
14,
13,
14,
14,
};
static c_float linsys_solver_L_x[33] = {
(c_float)-29.48010793999343448490,
(c_float)-99.97190999359341390118,
(c_float)-30.82743440492653519414,
(c_float)-100.00000000000002842171,
(c_float)-0.29481202769716091661,
(c_float)-0.14744180871308842917,
(c_float)-0.28241731217027055134,
(c_float)-33.88407780771444777201,
(c_float)-99.93233275026507556049,
(c_float)2.92000179648696756018,
(c_float)0.08622280509148315397,
(c_float)-0.08257770667037457601,
(c_float)-0.08620187253746279532,
(c_float)-1.31889132593264712945,
(c_float)1.26313474639814771194,
(c_float)1.31857113495883493393,
(c_float)3.21174604977709421405,
(c_float)0.10418014645541757990,
(c_float)-0.09977589531846385584,
(c_float)-0.10415485434689461530,
(c_float)-1.31743389967464574752,
(c_float)1.26173893333106867942,
(c_float)1.31711406252432428055,
(c_float)3.35757003410047527581,
(c_float)0.11392473350427950729,
(c_float)-0.11385237561850698740,
(c_float)-0.09904093536941280251,
(c_float)-1.53895645268926761773,
(c_float)1.26032734769236398620,
(c_float)1.76299270235654836902,
(c_float)-0.90091421562174400783,
(c_float)-1.05330492417058185772,
(c_float)-0.17059170238479920423,
};
static csc linsys_solver_L = {33, 15, 15, linsys_solver_L_p, linsys_solver_L_i, linsys_solver_L_x, -1};
static c_float linsys_solver_Dinv[15] = {
(c_float)-100.00000000000000000000,
(c_float)-100.00000000000000000000,
(c_float)0.99999900000099983810,
(c_float)0.99999900000099983810,
(c_float)0.99999900000099983810,
(c_float)-100.00000000000000000000,
(c_float)0.08623457412383600529,
(c_float)0.50248850997062644019,
(c_float)0.10418466900585875157,
(c_float)0.50248470515929544167,
(c_float)0.11392473350427947953,
(c_float)0.50248585440726634133,
(c_float)-0.08357563296290437815,
(c_float)-5.84027218143605342249,
(c_float)-5.22179333995010974689,
};
static c_int linsys_solver_P[15] = {
14,
13,
6,
7,
8,
12,
0,
3,
1,
4,
2,
5,
10,
11,
9,
};
static c_float linsys_solver_bp[15];
static c_float linsys_solver_sol[15];
static c_float linsys_solver_rho_inv_vec[6] = {
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
};
static c_int linsys_solver_Pdiag_idx[9] = {
0,
1,
2,
3,
4,
5,
6,
7,
8,
};
static c_int linsys_solver_KKT_p[16] = {
0,
1,
2,
3,
4,
5,
6,
8,
10,
12,
14,
16,
18,
26,
34,
42,
};
static c_int linsys_solver_KKT_i[42] = {
0,
1,
2,
3,
4,
5,
6,
5,
7,
5,
8,
1,
9,
1,
10,
0,
11,
0,
6,
8,
10,
7,
9,
11,
3,
12,
6,
8,
10,
7,
9,
11,
4,
13,
6,
8,
10,
7,
9,
11,
2,
14,
};
static c_float linsys_solver_KKT_x[42] = {
(c_float)-0.01000000000000000021,
(c_float)-0.01000000000000000021,
(c_float)1.00000100000000013978,
(c_float)1.00000100000000013978,
(c_float)1.00000100000000013978,
(c_float)-0.01000000000000000021,
(c_float)0.11496961244164007054,
(c_float)0.33884077807714446662,
(c_float)1.00000100000000013978,
(c_float)0.99932332750265073784,
(c_float)0.09503407119900471323,
(c_float)0.30827434404926534750,
(c_float)1.00000100000000013978,
(c_float)1.00000000000000022204,
(c_float)0.08695752173913044725,
(c_float)0.29480107939993432931,
(c_float)1.00000099999999991773,
(c_float)0.99971909993593410793,
(c_float)0.99986352304197678720,
(c_float)0.99995659101781164679,
(c_float)1.00000000000000022204,
(c_float)0.29488391230979432711,
(c_float)0.58976782461958865422,
(c_float)0.29488391230979432711,
(c_float)-0.14744195615489716356,
(c_float)-0.01000000000000000021,
(c_float)-0.95759395241855038705,
(c_float)-0.95768308591404205377,
(c_float)-0.99936486236529331606,
(c_float)-0.28241759458758275425,
(c_float)-0.56483518917516550850,
(c_float)-0.84725278376274792969,
(c_float)-0.28241759458758275425,
(c_float)-0.01000000000000000021,
(c_float)-0.99962078334930670742,
(c_float)-0.99971382873076597431,
(c_float)-0.86935411058646383520,
(c_float)-0.29481232250918865123,
(c_float)-0.58962464501837719144,
(c_float)0.58962464501837719144,
(c_float)-0.29481232250918865123,
(c_float)-0.01000000000000000021,
};
static csc linsys_solver_KKT = {42, 15, 15, linsys_solver_KKT_p, linsys_solver_KKT_i, linsys_solver_KKT_x, -1};
static c_int linsys_solver_PtoKKT[9] = {
6,
10,
14,
8,
12,
16,
2,
3,
4,
};
static c_int linsys_solver_AtoKKT[27] = {
34,
18,
26,
7,
35,
19,
27,
11,
36,
20,
28,
15,
37,
21,
29,
9,
38,
22,
30,
13,
39,
23,
31,
17,
40,
24,
32,
};
static c_int linsys_solver_rhotoKKT[6] = {
41,
25,
33,
5,
1,
0,
};
static QDLDL_float linsys_solver_D[15] = {
0,
0,
1,
1,
1,
0,
11,
1,
9,
1,
8,
1,
-11,
0,
0,
};
static QDLDL_int linsys_solver_etree[15] = {
10,
8,
14,
12,
13,
6,
7,
12,
9,
12,
11,
12,
13,
14,
-1,
};
static QDLDL_int linsys_solver_Lnz[15] = {
2,
2,
1,
1,
1,
2,
4,
3,
4,
3,
4,
3,
2,
1,
0,
};
static QDLDL_int   linsys_solver_iwork[45];
static QDLDL_bool  linsys_solver_bwork[15];
static QDLDL_float linsys_solver_fwork[15];
static qdldl_solver linsys_solver = {QDLDL_SOLVER, &solve_linsys_qdldl, &update_linsys_solver_matrices_qdldl, &update_linsys_solver_rho_vec_qdldl, &linsys_solver_L, linsys_solver_Dinv, linsys_solver_P, linsys_solver_bp, linsys_solver_sol, linsys_solver_rho_inv_vec, (c_float)0.00000100000000000000, 9, 6, linsys_solver_Pdiag_idx, 9, &linsys_solver_KKT, linsys_solver_PtoKKT, linsys_solver_AtoKKT, linsys_solver_rhotoKKT, linsys_solver_D, linsys_solver_etree, linsys_solver_Lnz, linsys_solver_iwork, linsys_solver_bwork, linsys_solver_fwork, };

// Define solution
static c_float xsolution[9];
static c_float ysolution[6];

static OSQPSolution solution = {xsolution, ysolution};

// Define info
static OSQPInfo info = {0, "Unsolved", OSQP_UNSOLVED, 0.0, 0.0, 0.0};

// Define workspace
static c_float work_rho_vec[6] = {
(c_float)100.00000000000000000000,
(c_float)100.00000000000000000000,
(c_float)100.00000000000000000000,
(c_float)100.00000000000000000000,
(c_float)100.00000000000000000000,
(c_float)100.00000000000000000000,
};
static c_float work_rho_inv_vec[6] = {
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
};
static c_int work_constr_type[6] = {
1,
1,
1,
1,
1,
1,
};
static c_float work_x[9];
static c_float work_y[6];
static c_float work_z[6];
static c_float work_xz_tilde[15];
static c_float work_x_prev[9];
static c_float work_z_prev[6];
static c_float work_Ax[6];
static c_float work_Px[9];
static c_float work_Aty[9];
static c_float work_delta_y[6];
static c_float work_Atdelta_y[9];
static c_float work_delta_x[9];
static c_float work_Pdelta_x[9];
static c_float work_Adelta_x[6];
static c_float work_D_temp[9];
static c_float work_D_temp_A[9];
static c_float work_E_temp[6];

OSQPWorkspace workspace_compute_Fd_pair = {
&data, (LinSysSolver *)&linsys_solver,
work_rho_vec, work_rho_inv_vec,
work_constr_type,
work_x, work_y, work_z, work_xz_tilde,
work_x_prev, work_z_prev,
work_Ax, work_Px, work_Aty,
work_delta_y, work_Atdelta_y,
work_delta_x, work_Pdelta_x, work_Adelta_x,
work_D_temp, work_D_temp_A, work_E_temp,
&settings, &scaling, &solution, &info};

