/*
 * This file was autogenerated by OSQP-Python on January 24, 2023 at 16:56:17.
 * 
 * This file contains the workspace variables needed by OSQP.
 */

#include "types.h"
#include "qdldl_interface.h"

// Define data structure
static c_int Pdata_p[7] = {
0,
1,
2,
3,
3,
3,
3,
};
static c_int Pdata_i[3] = {
0,
1,
2,
};
static c_float Pdata_x[3] = {
(c_float)0.00654038969233048783,
(c_float)0.00567016597615627952,
(c_float)0.00496277915632754429,
};
static csc Pdata = {3, 6, 6, Pdata_p, Pdata_i, Pdata_x, -1};
static c_int Adata_p[7] = {
0,
6,
12,
18,
20,
22,
28,
};
static c_int Adata_i[28] = {
0,
1,
2,
3,
4,
5,
0,
1,
2,
3,
4,
5,
0,
1,
2,
3,
4,
5,
4,
6,
5,
7,
0,
1,
2,
3,
4,
5,
};
static c_float Adata_x[28] = {
(c_float)0.15666723451816078061,
(c_float)0.62615344639907521973,
(c_float)-0.89180589352050543273,
(c_float)-0.95577479168647394570,
(c_float)0.93895269753505983257,
(c_float)-0.99986509666035128241,
(c_float)0.29174555381320876890,
(c_float)0.72876391701167897441,
(c_float)-0.94898283741049116458,
(c_float)-0.97891352795228592232,
(c_float)0.97139816258494926515,
(c_float)-0.99993487382539258945,
(c_float)0.40941155343652763099,
(c_float)0.81814955107975795290,
(c_float)-0.99879295306481530314,
(c_float)-0.99907359290106778626,
(c_float)0.99966514909156145574,
(c_float)-1.00000000000000022204,
(c_float)-0.25299545417614344167,
(c_float)-1.00000000000000000000,
(c_float)-0.17960530202677491007,
(c_float)-1.00000000000000000000,
(c_float)-1.00000000000000000000,
(c_float)-0.99917740988542758096,
(c_float)0.81319391590289780147,
(c_float)0.61006680473170704637,
(c_float)-0.33296074263633546053,
(c_float)0.23637387058592207456,
};
static csc Adata = {28, 8, 6, Adata_p, Adata_i, Adata_x, -1};
static c_float qdata[6] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)0.00000000000000000000,
};
static c_float ldata[8] = {
(c_float)-759835685651592728064007602176.00000000000000000000,
(c_float)-759210652327876158005111160832.00000000000000000000,
(c_float)-617893756657782153969687068672.00000000000000000000,
(c_float)-463550528866592952847297413120.00000000000000000000,
(c_float)-252995454176143442316898598912.00000000000000000000,
(c_float)-179605302026774929372839149568.00000000000000000000,
(c_float)-1000000000000000019884624838656.00000000000000000000,
(c_float)-1000000000000000019884624838656.00000000000000000000,
};
static c_float udata[8] = {
(c_float)-0.75983568565159265162,
(c_float)-0.75921065232787621202,
(c_float)-0.61789375665778212277,
(c_float)-0.46355052886659292577,
(c_float)-0.25299545417614344167,
(c_float)-0.17960530202677491007,
(c_float)-0.00000000000000000000,
(c_float)-0.00000000000000000000,
};
static OSQPData data = {6, 8, &Pdata, &Adata, qdata, ldata, udata};

// Define settings structure
static OSQPSettings settings = {(c_float)3.74629280326662161826, (c_float)0.00000100000000000000, 10, 1, 25, (c_float)5.00000000000000000000, 4000, (c_float)0.00100000000000000002, (c_float)0.00100000000000000002, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)1.00000000000000000000, (enum linsys_solver_type) LINSYS_SOLVER, 0, 25, 1, };

// Define scaling structure
static c_float Dscaling[6] = {
(c_float)0.20618567603048507109,
(c_float)0.19197937088399838479,
(c_float)0.17960530202677491007,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.31607401295249237805,
};
static c_float Dinvscaling[6] = {
(c_float)4.84999743557427098750,
(c_float)5.20889299405111572128,
(c_float)5.56776436283002151839,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)0.75983568565159254060,
};
static c_float Escaling[8] = {
(c_float)0.75983568565159265162,
(c_float)0.75921065232787621202,
(c_float)0.61789375665778212277,
(c_float)0.46355052886659292577,
(c_float)0.25299545417614344167,
(c_float)0.17960530202677491007,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
static c_float Einvscaling[8] = {
(c_float)1.31607401295249237805,
(c_float)1.31715749368613366244,
(c_float)1.61840120445470980748,
(c_float)2.15726212727025945526,
(c_float)3.95264018974731579092,
(c_float)5.56776436283002151839,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
static OSQPScaling scaling = {(c_float)0.07692307692307692735, Dscaling, Escaling, (c_float)13.00000000000000000000, Dinvscaling, Einvscaling};

// Define linsys_solver structure
static c_int linsys_solver_L_p[15] = {
0,
1,
2,
3,
4,
8,
12,
19,
25,
30,
34,
37,
39,
40,
40,
};
static c_int linsys_solver_L_i[40] = {
1,
5,
3,
4,
6,
7,
8,
13,
6,
7,
8,
13,
7,
8,
9,
10,
11,
12,
13,
8,
9,
10,
11,
12,
13,
9,
10,
11,
12,
13,
10,
11,
12,
13,
11,
12,
13,
12,
13,
13,
};
static c_float linsys_solver_L_x[40] = {
(c_float)3.74629280326662161826,
(c_float)-0.04794212933063768389,
(c_float)3.74629280326662161826,
(c_float)-0.06753219780988381493,
(c_float)-3.42022470779796661233,
(c_float)-3.51975078205739988491,
(c_float)1.17233139051976098521,
(c_float)-3.30598650404809824010,
(c_float)3.62898482614548800740,
(c_float)3.62922118343797039941,
(c_float)-0.85785305834165359595,
(c_float)3.62873158938000006657,
(c_float)1.01311585267665660304,
(c_float)-0.28699863582129248041,
(c_float)0.04193662745573940170,
(c_float)0.10475532700138952269,
(c_float)-0.13641044120197479139,
(c_float)-0.14071279372230799387,
(c_float)0.98319703925064971806,
(c_float)-0.57193451139221918034,
(c_float)9.29187439238053869417,
(c_float)6.51570808484844299358,
(c_float)-3.04969684169951404940,
(c_float)-0.59754089998235215830,
(c_float)0.32446277727247258005,
(c_float)-52.90995264765309968880,
(c_float)-46.27144264057420031122,
(c_float)32.29121492583519881236,
(c_float)20.19852121354930929442,
(c_float)0.42403722724422276968,
(c_float)0.86597291850421898030,
(c_float)-0.60105439356078882440,
(c_float)-0.37309865122627994261,
(c_float)-0.00417949965430230216,
(c_float)-0.45701871184656389646,
(c_float)-0.38167794749361327877,
(c_float)-0.05931607897905966792,
(c_float)0.37200953369811229354,
(c_float)0.08555832391024822958,
(c_float)0.08120116621932663148,
};
static csc linsys_solver_L = {40, 14, 14, linsys_solver_L_p, linsys_solver_L_i, linsys_solver_L_x, -1};
static c_float linsys_solver_Dinv[14] = {
(c_float)-3.74629280326662161826,
(c_float)0.26693047916531242869,
(c_float)-3.74629280326662161826,
(c_float)0.26693047916531242869,
(c_float)-3.52092976858896022918,
(c_float)-3.62922118343796951123,
(c_float)0.14374384427667916131,
(c_float)81.62258043907586113619,
(c_float)62.16212032207054249966,
(c_float)-0.02156482146933699079,
(c_float)-1.88076568433066171337,
(c_float)-2.37563895851503037449,
(c_float)-2.62173508878756322815,
(c_float)55.40268134631233465370,
};
static c_int linsys_solver_P[14] = {
13,
4,
12,
3,
10,
11,
1,
2,
5,
6,
7,
8,
9,
0,
};
static c_float linsys_solver_bp[14];
static c_float linsys_solver_sol[14];
static c_float linsys_solver_rho_inv_vec[8] = {
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
};
static c_int linsys_solver_Pdiag_idx[3] = {
0,
1,
2,
};
static c_int linsys_solver_KKT_p[15] = {
0,
1,
3,
4,
6,
8,
10,
13,
16,
19,
23,
27,
31,
35,
42,
};
static c_int linsys_solver_KKT_i[42] = {
0,
1,
0,
2,
3,
2,
3,
4,
1,
5,
6,
4,
5,
7,
4,
5,
8,
4,
5,
6,
7,
8,
9,
6,
7,
8,
10,
6,
7,
8,
11,
6,
7,
8,
12,
13,
9,
10,
11,
12,
4,
5,
};
static c_float linsys_solver_KKT_x[42] = {
(c_float)-0.26693055041721214238,
(c_float)0.00000100000000000000,
(c_float)-1.00000000000000000000,
(c_float)-0.26693055041721214238,
(c_float)0.00000100000000000000,
(c_float)-1.00000000000000000000,
(c_float)-0.25299545417614344167,
(c_float)-0.26693055041721214238,
(c_float)-0.17960530202677491007,
(c_float)-0.26693055041721214238,
(c_float)0.00567116597615627965,
(c_float)0.97139816258494926515,
(c_float)-0.99993487382539258945,
(c_float)0.00496377915632754442,
(c_float)0.99966514909156145574,
(c_float)-1.00000000000000022204,
(c_float)0.00000100000000000000,
(c_float)-0.33296074263633546053,
(c_float)0.23637387058592207456,
(c_float)0.29174555381320876890,
(c_float)0.40941155343652763099,
(c_float)-1.00000000000000000000,
(c_float)-0.26693055041721214238,
(c_float)0.72876391701167897441,
(c_float)0.81814955107975795290,
(c_float)-0.99917740988542758096,
(c_float)-0.26693055041721214238,
(c_float)-0.94898283741049116458,
(c_float)-0.99879295306481530314,
(c_float)0.81319391590289780147,
(c_float)-0.26693055041721214238,
(c_float)-0.97891352795228592232,
(c_float)-0.99907359290106778626,
(c_float)0.61006680473170704637,
(c_float)-0.26693055041721214238,
(c_float)0.00654138969233048796,
(c_float)0.15666723451816078061,
(c_float)0.62615344639907521973,
(c_float)-0.89180589352050543273,
(c_float)-0.95577479168647394570,
(c_float)0.93895269753505983257,
(c_float)-0.99986509666035128241,
};
static csc linsys_solver_KKT = {42, 14, 14, linsys_solver_KKT_p, linsys_solver_KKT_i, linsys_solver_KKT_x, -1};
static c_int linsys_solver_PtoKKT[3] = {
35,
10,
13,
};
static c_int linsys_solver_AtoKKT[28] = {
36,
37,
38,
39,
40,
41,
19,
23,
27,
31,
11,
12,
20,
24,
28,
32,
14,
15,
6,
5,
8,
2,
21,
25,
29,
33,
17,
18,
};
static c_int linsys_solver_rhotoKKT[8] = {
22,
26,
30,
34,
7,
9,
3,
0,
};
static QDLDL_float linsys_solver_D[14] = {
0,
3,
0,
3,
0,
0,
6,
0,
0,
-46,
0,
0,
0,
0,
};
static QDLDL_int linsys_solver_etree[14] = {
1,
5,
3,
4,
6,
6,
7,
8,
9,
10,
11,
12,
13,
-1,
};
static QDLDL_int linsys_solver_Lnz[14] = {
1,
1,
1,
1,
4,
4,
7,
6,
5,
4,
3,
2,
1,
0,
};
static QDLDL_int   linsys_solver_iwork[42];
static QDLDL_bool  linsys_solver_bwork[14];
static QDLDL_float linsys_solver_fwork[14];
static qdldl_solver linsys_solver = {QDLDL_SOLVER, &solve_linsys_qdldl, &update_linsys_solver_matrices_qdldl, &update_linsys_solver_rho_vec_qdldl, &linsys_solver_L, linsys_solver_Dinv, linsys_solver_P, linsys_solver_bp, linsys_solver_sol, linsys_solver_rho_inv_vec, (c_float)0.00000100000000000000, 6, 8, linsys_solver_Pdiag_idx, 3, &linsys_solver_KKT, linsys_solver_PtoKKT, linsys_solver_AtoKKT, linsys_solver_rhotoKKT, linsys_solver_D, linsys_solver_etree, linsys_solver_Lnz, linsys_solver_iwork, linsys_solver_bwork, linsys_solver_fwork, };

// Define solution
static c_float xsolution[6];
static c_float ysolution[8];

static OSQPSolution solution = {xsolution, ysolution};

// Define info
static OSQPInfo info = {0, "Unsolved", OSQP_UNSOLVED, 0.0, 0.0, 0.0};

// Define workspace
static c_float work_rho_vec[8] = {
(c_float)3.74629280326662161826,
(c_float)3.74629280326662161826,
(c_float)3.74629280326662161826,
(c_float)3.74629280326662161826,
(c_float)3.74629280326662161826,
(c_float)3.74629280326662161826,
(c_float)3.74629280326662161826,
(c_float)3.74629280326662161826,
};
static c_float work_rho_inv_vec[8] = {
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
(c_float)0.26693055041721214238,
};
static c_int work_constr_type[8] = {
0,
0,
0,
0,
0,
0,
0,
0,
};
static c_float work_x[6];
static c_float work_y[8];
static c_float work_z[8];
static c_float work_xz_tilde[14];
static c_float work_x_prev[6];
static c_float work_z_prev[8];
static c_float work_Ax[8];
static c_float work_Px[6];
static c_float work_Aty[6];
static c_float work_delta_y[8];
static c_float work_Atdelta_y[6];
static c_float work_delta_x[6];
static c_float work_Pdelta_x[6];
static c_float work_Adelta_x[8];
static c_float work_D_temp[6];
static c_float work_D_temp_A[6];
static c_float work_E_temp[8];

OSQPWorkspace workspace_hyperplane_rb = {
&data, (LinSysSolver *)&linsys_solver,
work_rho_vec, work_rho_inv_vec,
work_constr_type,
work_x, work_y, work_z, work_xz_tilde,
work_x_prev, work_z_prev,
work_Ax, work_Px, work_Aty,
work_delta_y, work_Atdelta_y,
work_delta_x, work_Pdelta_x, work_Adelta_x,
work_D_temp, work_D_temp_A, work_E_temp,
&settings, &scaling, &solution, &info};

