/*
 * This file was autogenerated by OSQP-Python on January 17, 2023 at 16:07:39.
 * 
 * This file contains the workspace variables needed by OSQP.
 */

#include "types.h"
#include "qdldl_interface.h"

// Define data structure
static c_int Pdata_p[7] = {
0,
1,
2,
3,
4,
5,
5,
};
static c_int Pdata_i[5] = {
0,
1,
2,
3,
4,
};
static c_float Pdata_x[5] = {
(c_float)0.13145932826636771984,
(c_float)0.11727156608114171210,
(c_float)0.10526315789473687790,
(c_float)1.00000000000000022204,
(c_float)1.00000000000000022204,
};
static csc Pdata = {5, 6, 6, Pdata_p, Pdata_i, Pdata_x, -1};
static c_int Adata_p[7] = {
0,
6,
12,
18,
19,
20,
26,
};
static c_int Adata_i[26] = {
0,
1,
2,
3,
4,
5,
0,
1,
2,
3,
4,
5,
0,
1,
2,
3,
4,
5,
0,
1,
0,
1,
2,
3,
4,
5,
};
static c_float Adata_x[26] = {
(c_float)0.97767087050322964981,
(c_float)0.99989138711451919228,
(c_float)0.19480513155724982211,
(c_float)0.74417894517076355054,
(c_float)-0.86855261513411508023,
(c_float)-0.93085356446959000021,
(c_float)0.98936503302933087589,
(c_float)0.99994720137312498309,
(c_float)0.36798578843546703165,
(c_float)0.87859362869009782759,
(c_float)-0.93753769310122769820,
(c_float)-0.96710740654309756970,
(c_float)0.99983219156488090107,
(c_float)1.00000000000000022204,
(c_float)0.52295478433440489852,
(c_float)0.99887496973766987107,
(c_float)-0.99927056460315411002,
(c_float)-0.99955133863821499229,
(c_float)-0.05341918519717696323,
(c_float)-0.04499212706658475835,
(c_float)-0.35847943557303396656,
(c_float)-0.30192808550947131119,
(c_float)-1.00000000000000000000,
(c_float)-0.95502995637471466139,
(c_float)0.63693879122837515627,
(c_float)0.47783831823548689188,
};
static csc Adata = {26, 6, 6, Adata_p, Adata_i, Adata_x, -1};
static c_float qdata[6] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
};
static c_float ldata[6] = {
(c_float)-0.00000000000000000000,
(c_float)-0.00000000000000000000,
(c_float)-759835685651592728064007602176.00000000000000000000,
(c_float)-725665841719791926137222856704.00000000000000000000,
(c_float)-483968823151108930227838910464.00000000000000000000,
(c_float)-363078606167065002735669608448.00000000000000000000,
};
static c_float udata[6] = {
(c_float)-0.00000000000000000000,
(c_float)-0.00000000000000000000,
(c_float)-0.75983568565159265162,
(c_float)-0.72566584171979198192,
(c_float)-0.48396882315110895112,
(c_float)-0.36307860616706499890,
};
static OSQPData data = {6, 6, &Pdata, &Adata, qdata, ldata, udata};

// Define settings structure
static OSQPSettings settings = {(c_float)0.10000000000000000555, (c_float)0.00000100000000000000, 10, 1, 0, (c_float)5.00000000000000000000, 4000, (c_float)0.00100000000000000002, (c_float)0.00100000000000000002, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)1.00000000000000000000, (enum linsys_solver_type) LINSYS_SOLVER, 0, 25, 1, };

// Define scaling structure
static c_float Dscaling[6] = {
(c_float)0.25637797123228800444,
(c_float)0.24214826664787600374,
(c_float)0.22941573387056179989,
(c_float)0.19611613513818404453,
(c_float)0.19611613513818404453,
(c_float)1.31607401295249237805,
};
static c_float Dinvscaling[6] = {
(c_float)3.90049111939481996103,
(c_float)4.12970125222563311240,
(c_float)4.35889894354067308768,
(c_float)5.09901951359278449161,
(c_float)5.09901951359278449161,
(c_float)0.75983568565159254060,
};
static c_float Escaling[6] = {
(c_float)0.27238546772063221280,
(c_float)0.22941573387056179989,
(c_float)0.75983568565159265162,
(c_float)0.72566584171979198192,
(c_float)0.48396882315110895112,
(c_float)0.36307860616706499890,
};
static c_float Einvscaling[6] = {
(c_float)3.67126781163536231034,
(c_float)4.35889894354067308768,
(c_float)1.31607401295249237805,
(c_float)1.37804474526463827111,
(c_float)2.06624879984835585489,
(c_float)2.75422452057080313637,
};
static OSQPScaling scaling = {(c_float)1.00000000000000000000, Dscaling, Escaling, (c_float)1.00000000000000000000, Dinvscaling, Einvscaling};

// Define linsys_solver structure
static c_int linsys_solver_L_p[13] = {
0,
1,
2,
6,
10,
17,
23,
28,
32,
35,
37,
38,
38,
};
static c_int linsys_solver_L_i[38] = {
3,
2,
4,
5,
6,
11,
4,
5,
6,
11,
5,
6,
7,
8,
9,
10,
11,
6,
7,
8,
9,
10,
11,
7,
8,
9,
10,
11,
8,
9,
10,
11,
9,
10,
11,
10,
11,
11,
};
static c_float linsys_solver_L_x[38] = {
(c_float)-0.04499208207450267755,
(c_float)-0.05341913177804517854,
(c_float)-76.97178480824162249974,
(c_float)-77.78612112239780174150,
(c_float)27.88940487276092028424,
(c_float)-76.06198859408233658996,
(c_float)-83.16060616815600781138,
(c_float)-83.16499716581044765462,
(c_float)25.10984837567375294043,
(c_float)-83.15596437549724839755,
(c_float)1.00434553408753557413,
(c_float)-0.33056778485980586879,
(c_float)0.00230818196515741305,
(c_float)0.00551095730372296987,
(c_float)-0.00588068252328999199,
(c_float)-0.00606615783626764538,
(c_float)0.99358931219889412567,
(c_float)-0.28166250314995788795,
(c_float)0.67252698153476098142,
(c_float)0.51069190574098544122,
(c_float)-0.25283369115188963905,
(c_float)-0.12383824270848069193,
(c_float)0.49195587089126019409,
(c_float)-5.97841770019365981170,
(c_float)-4.52264016871154428401,
(c_float)2.22468894596271438147,
(c_float)1.07511976163559852537,
(c_float)0.15242363951329709892,
(c_float)0.25551370249815902325,
(c_float)-0.12578108090128106711,
(c_float)-0.06088127477942521792,
(c_float)0.00788075911569094401,
(c_float)-0.08000606538348249697,
(c_float)-0.03888695319580105780,
(c_float)0.00497462306087604299,
(c_float)0.01868069603538549672,
(c_float)-0.00233305696231415546,
(c_float)-0.00109476228196096694,
};
static csc linsys_solver_L = {38, 12, 12, linsys_solver_L_p, linsys_solver_L_i, linsys_solver_L_x, -1};
static c_float linsys_solver_Dinv[12] = {
(c_float)0.99999900000099983810,
(c_float)0.99999900000099983810,
(c_float)-77.79917648045653777444,
(c_float)-83.16499716581043344377,
(c_float)0.00627247583383833476,
(c_float)4.38499977284041975167,
(c_float)7.15843398121376406351,
(c_float)-0.06623870555055640097,
(c_float)-0.08377981020541315493,
(c_float)-0.09618872696498781405,
(c_float)-0.09907659960135045685,
(c_float)5.11028460257743244455,
};
static c_int linsys_solver_P[12] = {
4,
3,
6,
7,
1,
2,
5,
8,
9,
10,
11,
0,
};
static c_float linsys_solver_bp[12];
static c_float linsys_solver_sol[12];
static c_float linsys_solver_rho_inv_vec[6] = {
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
static c_int linsys_solver_Pdiag_idx[5] = {
0,
1,
2,
3,
4,
};
static c_int linsys_solver_KKT_p[13] = {
0,
1,
2,
4,
6,
9,
12,
15,
19,
23,
27,
31,
38,
};
static c_int linsys_solver_KKT_i[38] = {
0,
1,
1,
2,
0,
3,
4,
2,
3,
5,
2,
3,
6,
2,
3,
4,
5,
6,
7,
4,
5,
6,
8,
4,
5,
6,
9,
4,
5,
6,
10,
11,
2,
3,
7,
8,
9,
10,
};
static c_float linsys_solver_KKT_x[38] = {
(c_float)1.00000100000000013978,
(c_float)1.00000100000000013978,
(c_float)-0.05341918519717696323,
(c_float)-0.01000000000000000021,
(c_float)-0.04499212706658475835,
(c_float)-0.01000000000000000021,
(c_float)0.11727256608114171310,
(c_float)0.98936503302933087589,
(c_float)0.99994720137312498309,
(c_float)0.10526415789473687890,
(c_float)0.99983219156488090107,
(c_float)1.00000000000000022204,
(c_float)0.00000100000000000000,
(c_float)-0.35847943557303396656,
(c_float)-0.30192808550947131119,
(c_float)0.36798578843546703165,
(c_float)0.52295478433440489852,
(c_float)-1.00000000000000000000,
(c_float)-10.00000000000000000000,
(c_float)0.87859362869009782759,
(c_float)0.99887496973766987107,
(c_float)-0.95502995637471466139,
(c_float)-10.00000000000000000000,
(c_float)-0.93753769310122769820,
(c_float)-0.99927056460315411002,
(c_float)0.63693879122837515627,
(c_float)-10.00000000000000000000,
(c_float)-0.96710740654309756970,
(c_float)-0.99955133863821499229,
(c_float)0.47783831823548689188,
(c_float)-10.00000000000000000000,
(c_float)0.13146032826636772084,
(c_float)0.97767087050322964981,
(c_float)0.99989138711451919228,
(c_float)0.19480513155724982211,
(c_float)0.74417894517076355054,
(c_float)-0.86855261513411508023,
(c_float)-0.93085356446959000021,
};
static csc linsys_solver_KKT = {38, 12, 12, linsys_solver_KKT_p, linsys_solver_KKT_i, linsys_solver_KKT_x, -1};
static c_int linsys_solver_PtoKKT[5] = {
31,
6,
9,
1,
0,
};
static c_int linsys_solver_AtoKKT[26] = {
32,
33,
34,
35,
36,
37,
7,
8,
15,
19,
23,
27,
10,
11,
16,
20,
24,
28,
2,
4,
13,
14,
17,
21,
25,
29,
};
static c_int linsys_solver_rhotoKKT[6] = {
3,
5,
18,
22,
26,
30,
};
static QDLDL_float linsys_solver_D[12] = {
1,
1,
0,
0,
159,
0,
0,
-15,
-11,
-10,
-10,
0,
};
static QDLDL_int linsys_solver_etree[12] = {
3,
2,
4,
4,
5,
6,
7,
8,
9,
10,
11,
-1,
};
static QDLDL_int linsys_solver_Lnz[12] = {
1,
1,
4,
4,
7,
6,
5,
4,
3,
2,
1,
0,
};
static QDLDL_int   linsys_solver_iwork[36];
static QDLDL_bool  linsys_solver_bwork[12];
static QDLDL_float linsys_solver_fwork[12];
static qdldl_solver linsys_solver = {QDLDL_SOLVER, &solve_linsys_qdldl, &update_linsys_solver_matrices_qdldl, &update_linsys_solver_rho_vec_qdldl, &linsys_solver_L, linsys_solver_Dinv, linsys_solver_P, linsys_solver_bp, linsys_solver_sol, linsys_solver_rho_inv_vec, (c_float)0.00000100000000000000, 6, 6, linsys_solver_Pdiag_idx, 5, &linsys_solver_KKT, linsys_solver_PtoKKT, linsys_solver_AtoKKT, linsys_solver_rhotoKKT, linsys_solver_D, linsys_solver_etree, linsys_solver_Lnz, linsys_solver_iwork, linsys_solver_bwork, linsys_solver_fwork, };

// Define solution
static c_float xsolution[6];
static c_float ysolution[6];

static OSQPSolution solution = {xsolution, ysolution};

// Define info
static OSQPInfo info = {0, "Unsolved", OSQP_UNSOLVED, 0.0, 0.0, 0.0};

// Define workspace
static c_float work_rho_vec[6] = {
(c_float)100.00000000000000000000,
(c_float)100.00000000000000000000,
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
};
static c_float work_rho_inv_vec[6] = {
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
static c_int work_constr_type[6] = {
1,
1,
0,
0,
0,
0,
};
static c_float work_x[6];
static c_float work_y[6];
static c_float work_z[6];
static c_float work_xz_tilde[12];
static c_float work_x_prev[6];
static c_float work_z_prev[6];
static c_float work_Ax[6];
static c_float work_Px[6];
static c_float work_Aty[6];
static c_float work_delta_y[6];
static c_float work_Atdelta_y[6];
static c_float work_delta_x[6];
static c_float work_Pdelta_x[6];
static c_float work_Adelta_x[6];
static c_float work_D_temp[6];
static c_float work_D_temp_A[6];
static c_float work_E_temp[6];

OSQPWorkspace workspace_hyperplane_rb = {
&data, (LinSysSolver *)&linsys_solver,
work_rho_vec, work_rho_inv_vec,
work_constr_type,
work_x, work_y, work_z, work_xz_tilde,
work_x_prev, work_z_prev,
work_Ax, work_Px, work_Aty,
work_delta_y, work_Atdelta_y,
work_delta_x, work_Pdelta_x, work_Adelta_x,
work_D_temp, work_D_temp_A, work_E_temp,
&settings, &scaling, &solution, &info};

