/*
 * This file was autogenerated by OSQP-Python on January 06, 2023 at 15:02:35.
 * 
 * This file contains the workspace variables needed by OSQP.
 */

#include "types.h"
#include "qdldl_interface.h"

// Define data structure
static c_int Pdata_p[4] = {
0,
1,
2,
3,
};
static c_int Pdata_i[3] = {
0,
1,
2,
};
static c_float Pdata_x[3] = {
(c_float)0.74940629208735720646,
(c_float)0.47982910397007522141,
(c_float)0.33333333333333342585,
};
static csc Pdata = {3, 3, 3, Pdata_p, Pdata_i, Pdata_x, -1};
static c_int Adata_p[4] = {
0,
2,
4,
6,
};
static c_int Adata_i[6] = {
0,
1,
0,
1,
0,
1,
};
static c_float Adata_x[6] = {
(c_float)0.49946385587459879440,
(c_float)-0.99960411636297785698,
(c_float)0.79931633234139665145,
(c_float)-0.99982196745436835439,
(c_float)0.99932332750265073784,
(c_float)-1.00000000000000022204,
};
static csc Adata = {6, 2, 3, Adata_p, Adata_i, Adata_x, -1};
static c_float qdata[3] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
};
static c_float ldata[2] = {
(c_float)-815944080147232457481456189440.00000000000000000000,
(c_float)-408248290463863089863059308544.00000000000000000000,
};
static c_float udata[2] = {
(c_float)-0.81594408014723240896,
(c_float)-0.40824829046386307274,
};
static OSQPData data = {3, 2, &Pdata, &Adata, qdata, ldata, udata};

// Define settings structure
static OSQPSettings settings = {(c_float)0.10000000000000000555, (c_float)0.00000100000000000000, 10, 1, 0, (c_float)5.00000000000000000000, 4000, (c_float)0.00100000000000000002, (c_float)0.00100000000000000002, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)1.00000000000000000000, (enum linsys_solver_type) LINSYS_SOLVER, 0, 25, 1, };

// Define scaling structure
static c_float Dscaling[3] = {
(c_float)0.61213000746873924562,
(c_float)0.48981073077775416635,
(c_float)0.40824829046386307274,
};
static c_float Dinvscaling[3] = {
(c_float)1.63363989315793967094,
(c_float)2.04160492444118846223,
(c_float)2.44948974278317788134,
};
static c_float Escaling[2] = {
(c_float)0.81594408014723240896,
(c_float)0.40824829046386307274,
};
static c_float Einvscaling[2] = {
(c_float)1.22557418373518411947,
(c_float)2.44948974278317788134,
};
static OSQPScaling scaling = {(c_float)1.00000000000000000000, Dscaling, Escaling, (c_float)1.00000000000000000000, Dinvscaling, Einvscaling};

// Define linsys_solver structure
static c_int linsys_solver_L_p[6] = {
0,
2,
4,
6,
7,
7,
};
static c_int linsys_solver_L_i[7] = {
3,
4,
3,
4,
3,
4,
4,
};
static c_float linsys_solver_L_x[7] = {
(c_float)2.99796098862498583415,
(c_float)-2.99999100002699981005,
(c_float)0.66647851061526242056,
(c_float)-1.33385960734213870893,
(c_float)1.66583198037788449142,
(c_float)-2.08369995792661377720,
(c_float)-0.36354618656427589718,
};
static csc linsys_solver_L = {7, 5, 5, linsys_solver_L_p, linsys_solver_L_i, linsys_solver_L_x, -1};
static c_float linsys_solver_Dinv[5] = {
(c_float)2.99999100002699936596,
(c_float)1.33438786966518008192,
(c_float)2.08407099039030985210,
(c_float)-0.06821123744127029209,
(c_float)-0.06906527887127723864,
};
static c_int linsys_solver_P[5] = {
2,
0,
1,
3,
4,
};
static c_float linsys_solver_bp[5];
static c_float linsys_solver_sol[5];
static c_float linsys_solver_rho_inv_vec[2] = {
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
static c_int linsys_solver_Pdiag_idx[3] = {
0,
1,
2,
};
static c_int linsys_solver_KKT_p[6] = {
0,
1,
2,
3,
7,
11,
};
static c_int linsys_solver_KKT_i[11] = {
0,
1,
2,
1,
2,
0,
3,
1,
2,
0,
4,
};
static c_float linsys_solver_KKT_x[11] = {
(c_float)0.33333433333333339910,
(c_float)0.74940729208735723521,
(c_float)0.47983010397007519465,
(c_float)0.49946385587459879440,
(c_float)0.79931633234139665145,
(c_float)0.99932332750265073784,
(c_float)-10.00000000000000000000,
(c_float)-0.99960411636297785698,
(c_float)-0.99982196745436835439,
(c_float)-1.00000000000000022204,
(c_float)-10.00000000000000000000,
};
static csc linsys_solver_KKT = {11, 5, 5, linsys_solver_KKT_p, linsys_solver_KKT_i, linsys_solver_KKT_x, -1};
static c_int linsys_solver_PtoKKT[3] = {
1,
2,
0,
};
static c_int linsys_solver_AtoKKT[6] = {
3,
7,
4,
8,
5,
9,
};
static c_int linsys_solver_rhotoKKT[2] = {
6,
10,
};
static QDLDL_float linsys_solver_D[5] = {
0,
0,
0,
-14,
-14,
};
static QDLDL_int linsys_solver_etree[5] = {
3,
3,
3,
4,
-1,
};
static QDLDL_int linsys_solver_Lnz[5] = {
2,
2,
2,
1,
0,
};
static QDLDL_int   linsys_solver_iwork[15];
static QDLDL_bool  linsys_solver_bwork[5];
static QDLDL_float linsys_solver_fwork[5];
static qdldl_solver linsys_solver = {QDLDL_SOLVER, &solve_linsys_qdldl, &update_linsys_solver_matrices_qdldl, &update_linsys_solver_rho_vec_qdldl, &linsys_solver_L, linsys_solver_Dinv, linsys_solver_P, linsys_solver_bp, linsys_solver_sol, linsys_solver_rho_inv_vec, (c_float)0.00000100000000000000, 3, 2, linsys_solver_Pdiag_idx, 3, &linsys_solver_KKT, linsys_solver_PtoKKT, linsys_solver_AtoKKT, linsys_solver_rhotoKKT, linsys_solver_D, linsys_solver_etree, linsys_solver_Lnz, linsys_solver_iwork, linsys_solver_bwork, linsys_solver_fwork, };

// Define solution
static c_float xsolution[3];
static c_float ysolution[2];

static OSQPSolution solution = {xsolution, ysolution};

// Define info
static OSQPInfo info = {0, "Unsolved", OSQP_UNSOLVED, 0.0, 0.0, 0.0};

// Define workspace
static c_float work_rho_vec[2] = {
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
};
static c_float work_rho_inv_vec[2] = {
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
static c_int work_constr_type[2] = {
0,
0,
};
static c_float work_x[3];
static c_float work_y[2];
static c_float work_z[2];
static c_float work_xz_tilde[5];
static c_float work_x_prev[3];
static c_float work_z_prev[2];
static c_float work_Ax[2];
static c_float work_Px[3];
static c_float work_Aty[3];
static c_float work_delta_y[2];
static c_float work_Atdelta_y[3];
static c_float work_delta_x[3];
static c_float work_Pdelta_x[3];
static c_float work_Adelta_x[2];
static c_float work_D_temp[3];
static c_float work_D_temp_A[3];
static c_float work_E_temp[2];

OSQPWorkspace workspace_hyperplane = {
&data, (LinSysSolver *)&linsys_solver,
work_rho_vec, work_rho_inv_vec,
work_constr_type,
work_x, work_y, work_z, work_xz_tilde,
work_x_prev, work_z_prev,
work_Ax, work_Px, work_Aty,
work_delta_y, work_Atdelta_y,
work_delta_x, work_Pdelta_x, work_Adelta_x,
work_D_temp, work_D_temp_A, work_E_temp,
&settings, &scaling, &solution, &info};

