/*
 * This file was autogenerated by OSQP-Python on January 12, 2023 at 10:37:33.
 * 
 * This file contains the workspace variables needed by OSQP.
 */

#include "types.h"
#include "qdldl_interface.h"

// Define data structure
static c_int Pdata_p[5] = {
0,
1,
2,
3,
4,
};
static c_int Pdata_i[4] = {
0,
1,
2,
3,
};
static c_float Pdata_x[4] = {
(c_float)0.36716667132992242273,
(c_float)0.28118530728753876602,
(c_float)0.22222222222222220989,
(c_float)1.00000000000000022204,
};
static csc Pdata = {4, 4, 4, Pdata_p, Pdata_i, Pdata_x, -1};
static c_int Adata_p[5] = {
0,
3,
6,
9,
10,
};
static c_int Adata_i[10] = {
0,
1,
2,
0,
1,
2,
0,
1,
2,
0,
};
static c_float Adata_x[10] = {
(c_float)0.99975460586769882010,
(c_float)0.42800682032148928968,
(c_float)-0.85659327375274163519,
(c_float)0.99988498411907555941,
(c_float)0.74910961439883838597,
(c_float)-0.93702107438902426662,
(c_float)1.00000000000000000000,
(c_float)0.99892771174919781085,
(c_float)-0.99960411636297763494,
(c_float)-0.06537204504606133892,
};
static csc Adata = {10, 3, 4, Adata_p, Adata_i, Adata_x, -1};
static c_float qdata[4] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
};
static c_float ldata[3] = {
(c_float)-0.00000000000000000000,
(c_float)-998927711749197830623963643904.00000000000000000000,
(c_float)-499802058181488918717154721792.00000000000000000000,
};
static c_float udata[3] = {
(c_float)-0.00000000000000000000,
(c_float)-0.99892771174919781085,
(c_float)-0.49980205818148892849,
};
static OSQPData data = {4, 3, &Pdata, &Adata, qdata, ldata, udata};

// Define settings structure
static OSQPSettings settings = {(c_float)0.10000000000000000555, (c_float)0.00000100000000000000, 10, 1, 0, (c_float)5.00000000000000000000, 4000, (c_float)0.00100000000000000002, (c_float)0.00100000000000000002, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)1.00000000000000000000, (enum linsys_solver_type) LINSYS_SOLVER, 0, 25, 1, };

// Define scaling structure
static c_float Dscaling[4] = {
(c_float)0.42846625965758527999,
(c_float)0.37495686904465341804,
(c_float)0.33333333333333331483,
(c_float)0.19611613513818404453,
};
static c_float Dinvscaling[4] = {
(c_float)2.33390606018584456649,
(c_float)2.66697341096292994678,
(c_float)3.00000000000000000000,
(c_float)5.09901951359278449161,
};
static c_float Escaling[3] = {
(c_float)0.33333333333333331483,
(c_float)0.99892771174919781085,
(c_float)0.49980205818148892849,
};
static c_float Einvscaling[3] = {
(c_float)3.00000000000000000000,
(c_float)1.00107343928713765635,
(c_float)2.00079208084589055261,
};
static OSQPScaling scaling = {(c_float)1.00000000000000000000, Dscaling, Escaling, (c_float)1.00000000000000000000, Dinvscaling, Einvscaling};

// Define linsys_solver structure
static c_int linsys_solver_L_p[8] = {
0,
1,
4,
8,
11,
13,
14,
14,
};
static c_int linsys_solver_L_i[14] = {
1,
2,
3,
6,
3,
4,
5,
6,
4,
5,
6,
5,
6,
6,
};
static c_float linsys_solver_L_x[14] = {
(c_float)-0.06537197967408164834,
(c_float)-70.05184321426253291065,
(c_float)-70.05990121551830895896,
(c_float)-70.04270892685042326775,
(c_float)0.99611618428950887694,
(c_float)0.01065211386982648466,
(c_float)-0.01332415842884223517,
(c_float)0.99587174322279392591,
(c_float)0.50309080461838018294,
(c_float)-0.13182502695279924021,
(c_float)0.55749555401590134007,
(c_float)-0.00427198155214857014,
(c_float)0.04527864815302018453,
(c_float)-0.01112836920968490913,
};
static csc linsys_solver_L = {14, 7, 7, linsys_solver_L_p, linsys_solver_L_i, linsys_solver_L_x, -1};
static c_float linsys_solver_Dinv[7] = {
(c_float)0.99999900000099983810,
(c_float)-70.05990121551830895896,
(c_float)0.01421969984776503236,
(c_float)1.99064527029635685018,
(c_float)-0.09866677036882356977,
(c_float)-0.09979014328375625242,
(c_float)1.94914552769865712101,
};
static c_int linsys_solver_P[7] = {
3,
4,
1,
2,
5,
6,
0,
};
static c_float linsys_solver_bp[7];
static c_float linsys_solver_sol[7];
static c_float linsys_solver_rho_inv_vec[3] = {
(c_float)0.01000000000000000021,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
static c_int linsys_solver_Pdiag_idx[4] = {
0,
1,
2,
3,
};
static c_int linsys_solver_KKT_p[8] = {
0,
1,
3,
5,
7,
10,
13,
17,
};
static c_int linsys_solver_KKT_i[17] = {
0,
0,
1,
2,
1,
3,
1,
2,
3,
4,
2,
3,
5,
6,
1,
4,
5,
};
static c_float linsys_solver_KKT_x[17] = {
(c_float)1.00000100000000013978,
(c_float)-0.06537204504606133892,
(c_float)-0.01000000000000000021,
(c_float)0.28118630728753873926,
(c_float)0.99988498411907555941,
(c_float)0.22222322222222221089,
(c_float)1.00000000000000000000,
(c_float)0.74910961439883838597,
(c_float)0.99892771174919781085,
(c_float)-10.00000000000000000000,
(c_float)-0.93702107438902426662,
(c_float)-0.99960411636297763494,
(c_float)-10.00000000000000000000,
(c_float)0.36716767132992239597,
(c_float)0.99975460586769882010,
(c_float)0.42800682032148928968,
(c_float)-0.85659327375274163519,
};
static csc linsys_solver_KKT = {17, 7, 7, linsys_solver_KKT_p, linsys_solver_KKT_i, linsys_solver_KKT_x, -1};
static c_int linsys_solver_PtoKKT[4] = {
13,
3,
5,
0,
};
static c_int linsys_solver_AtoKKT[10] = {
14,
15,
16,
4,
7,
10,
6,
8,
11,
1,
};
static c_int linsys_solver_rhotoKKT[3] = {
2,
9,
12,
};
static QDLDL_float linsys_solver_D[7] = {
1,
0,
70,
0,
-10,
-10,
0,
};
static QDLDL_int linsys_solver_etree[7] = {
1,
2,
3,
4,
5,
6,
-1,
};
static QDLDL_int linsys_solver_Lnz[7] = {
1,
3,
4,
3,
2,
1,
0,
};
static QDLDL_int   linsys_solver_iwork[21];
static QDLDL_bool  linsys_solver_bwork[7];
static QDLDL_float linsys_solver_fwork[7];
static qdldl_solver linsys_solver = {QDLDL_SOLVER, &solve_linsys_qdldl, &update_linsys_solver_matrices_qdldl, &update_linsys_solver_rho_vec_qdldl, &linsys_solver_L, linsys_solver_Dinv, linsys_solver_P, linsys_solver_bp, linsys_solver_sol, linsys_solver_rho_inv_vec, (c_float)0.00000100000000000000, 4, 3, linsys_solver_Pdiag_idx, 4, &linsys_solver_KKT, linsys_solver_PtoKKT, linsys_solver_AtoKKT, linsys_solver_rhotoKKT, linsys_solver_D, linsys_solver_etree, linsys_solver_Lnz, linsys_solver_iwork, linsys_solver_bwork, linsys_solver_fwork, };

// Define solution
static c_float xsolution[4];
static c_float ysolution[3];

static OSQPSolution solution = {xsolution, ysolution};

// Define info
static OSQPInfo info = {0, "Unsolved", OSQP_UNSOLVED, 0.0, 0.0, 0.0};

// Define workspace
static c_float work_rho_vec[3] = {
(c_float)100.00000000000000000000,
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
};
static c_float work_rho_inv_vec[3] = {
(c_float)0.01000000000000000021,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
static c_int work_constr_type[3] = {
1,
0,
0,
};
static c_float work_x[4];
static c_float work_y[3];
static c_float work_z[3];
static c_float work_xz_tilde[7];
static c_float work_x_prev[4];
static c_float work_z_prev[3];
static c_float work_Ax[3];
static c_float work_Px[4];
static c_float work_Aty[4];
static c_float work_delta_y[3];
static c_float work_Atdelta_y[4];
static c_float work_delta_x[4];
static c_float work_Pdelta_x[4];
static c_float work_Adelta_x[3];
static c_float work_D_temp[4];
static c_float work_D_temp_A[4];
static c_float work_E_temp[3];

OSQPWorkspace workspace_hyperplane = {
&data, (LinSysSolver *)&linsys_solver,
work_rho_vec, work_rho_inv_vec,
work_constr_type,
work_x, work_y, work_z, work_xz_tilde,
work_x_prev, work_z_prev,
work_Ax, work_Px, work_Aty,
work_delta_y, work_Atdelta_y,
work_delta_x, work_Pdelta_x, work_Adelta_x,
work_D_temp, work_D_temp_A, work_E_temp,
&settings, &scaling, &solution, &info};

