/*
 * This file was autogenerated by OSQP-Python on January 04, 2023 at 13:46:00.
 * 
 * This file contains the workspace variables needed by OSQP.
 */

#include "types.h"
#include "qdldl_interface.h"

// Define data structure
static c_int Pdata_i[6] = {
0,
1,
2,
3,
4,
5,
};
static c_int Pdata_p[7] = {
0,
1,
2,
3,
4,
5,
6,
};
static c_float Pdata_x[6] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
static csc Pdata = {6, 6, 6, Pdata_p, Pdata_i, Pdata_x, -1};
static c_int Adata_i[30] = {
0,
4,
5,
6,
7,
1,
3,
5,
6,
7,
2,
3,
4,
6,
7,
0,
4,
5,
6,
7,
1,
3,
5,
6,
7,
2,
3,
4,
6,
7,
};
static c_int Adata_p[7] = {
0,
5,
10,
15,
20,
25,
30,
};
static c_float Adata_x[30] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)-0.86315699236625065272,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)-1.00000000000000000000,
(c_float)-0.99688554047933186641,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)0.03549999999999999684,
(c_float)0.04100000000000000172,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)0.86315699236625065272,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)-1.00000000000000000000,
(c_float)-0.99688554047933186641,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)-0.03549999999999999684,
(c_float)0.04100000000000000172,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
static csc Adata = {30, 8, 6, Adata_p, Adata_i, Adata_x, -1};
static c_float qdata[6] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
static c_float ldata[8] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.09810000000000000664,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)-1000000000000000019884624838656.00000000000000000000,
(c_float)-1000000000000000019884624838656.00000000000000000000,
};
static c_float udata[8] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.09810000000000000664,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
};
static OSQPData data = {6, 8, &Pdata, &Adata, qdata, ldata, udata};

// Define settings structure
static OSQPSettings settings = {(c_float)0.10000000000000000555, (c_float)0.00000100000000000000, 10, 1, 0, (c_float)5.00000000000000000000, 4000, (c_float)0.00100000000000000002, (c_float)0.00100000000000000002, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)1.00000000000000000000, (enum linsys_solver_type) LINSYS_SOLVER, 0, 25, 1, };

// Define scaling structure
static c_float Dscaling[6] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
static c_float Dinvscaling[6] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
static c_float Escaling[8] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)24.31428147510565551670,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
static c_float Einvscaling[8] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)0.04112809177700179480,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
static OSQPScaling scaling = {(c_float)1.00000000000000000000, Dscaling, Escaling, (c_float)1.00000000000000000000, Dinvscaling, Einvscaling};

// Define linsys_solver structure
static c_int linsys_solver_L_i[43] = {
8,
9,
2,
3,
3,
7,
11,
12,
13,
7,
11,
12,
13,
5,
6,
6,
7,
10,
11,
12,
7,
10,
11,
12,
10,
11,
12,
13,
9,
10,
11,
12,
13,
10,
11,
12,
13,
11,
12,
13,
12,
13,
13,
};
static c_int linsys_solver_L_p[15] = {
0,
2,
4,
9,
13,
15,
20,
24,
28,
33,
37,
40,
42,
43,
43,
};
static c_float linsys_solver_L_x[43] = {
(c_float)-100.00000000000000000000,
(c_float)-100.00000000000000000000,
(c_float)-100.00000000000000000000,
(c_float)-100.00000000000000000000,
(c_float)0.99009900009802975784,
(c_float)-0.00854610875069447551,
(c_float)0.00990099000098029758,
(c_float)0.00990099000098029758,
(c_float)0.00990099000098029758,
(c_float)0.86315612921012530023,
(c_float)0.00497512435335758368,
(c_float)0.00497512435335758368,
(c_float)0.00497512435335758368,
(c_float)-100.00000000000000000000,
(c_float)-100.00000000000000000000,
(c_float)0.99009900009802975784,
(c_float)-0.00987015376840770509,
(c_float)-0.00990099000098029758,
(c_float)0.00990099000098029758,
(c_float)0.00990099000098029758,
(c_float)-0.00495962952994875948,
(c_float)-0.00497512435335758368,
(c_float)0.00497512435335758368,
(c_float)0.00497512435335758368,
(c_float)0.00656918989702577963,
(c_float)-0.00656918989702578830,
(c_float)-0.00656918989702578830,
(c_float)-0.00000000000000000689,
(c_float)0.99009900009802975784,
(c_float)0.00035148514503480053,
(c_float)0.00990099000098029758,
(c_float)0.00990099000098029758,
(c_float)0.00040594059004019219,
(c_float)-0.03549996450003565368,
(c_float)0.00497512435335758368,
(c_float)0.00497512435335758368,
(c_float)0.00020398009848765971,
(c_float)-0.44118854058766099335,
(c_float)-0.44118854058766099335,
(c_float)0.00000000000000000782,
(c_float)0.00253599213519346703,
(c_float)0.00103319405673760515,
(c_float)0.00103058051266280881,
};
static csc linsys_solver_L = {43, 14, 14, linsys_solver_L_p, linsys_solver_L_i, linsys_solver_L_x, -1};
static c_float linsys_solver_Dinv[14] = {
(c_float)-100.00000000000000000000,
(c_float)-100.00000000000000000000,
(c_float)0.00990099000098029758,
(c_float)0.50248706217718097644,
(c_float)-100.00000000000000000000,
(c_float)0.00990099000098029758,
(c_float)0.50248706217718097644,
(c_float)-0.66226618917377466644,
(c_float)0.00990099000098029758,
(c_float)0.50248706217718097644,
(c_float)-44.63172971578617165278,
(c_float)-0.09974640078648064345,
(c_float)-0.09974704228525577143,
(c_float)-50.13630773995863876280,
};
static c_int linsys_solver_P[14] = {
8,
6,
0,
3,
7,
1,
4,
11,
2,
5,
9,
12,
13,
10,
};
static c_float linsys_solver_bp[14];
static c_float linsys_solver_sol[14];
static c_float linsys_solver_rho_inv_vec[8] = {
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
static c_int linsys_solver_Pdiag_idx[6] = {
0,
1,
2,
3,
4,
5,
};
static c_int linsys_solver_KKT_i[44] = {
0,
1,
2,
1,
3,
1,
4,
5,
4,
6,
4,
2,
5,
3,
6,
7,
8,
0,
9,
0,
5,
8,
6,
9,
10,
2,
5,
8,
3,
6,
9,
11,
2,
5,
8,
3,
6,
9,
12,
2,
8,
3,
9,
13,
};
static c_int linsys_solver_KKT_p[15] = {
0,
1,
2,
4,
6,
7,
9,
11,
16,
18,
20,
25,
32,
39,
44,
};
static c_float linsys_solver_KKT_x[44] = {
(c_float)-0.01000000000000000021,
(c_float)-0.01000000000000000021,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)-0.01000000000000000021,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)-0.86315699236625065272,
(c_float)-0.99688554047933186641,
(c_float)0.86315699236625065272,
(c_float)-0.99688554047933186641,
(c_float)-0.01000000000000000021,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)-1.00000000000000000000,
(c_float)0.03549999999999999684,
(c_float)-1.00000000000000000000,
(c_float)-0.03549999999999999684,
(c_float)-0.01000000000000000021,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)-10.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)-10.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)0.04100000000000000172,
(c_float)1.00000000000000000000,
(c_float)0.04100000000000000172,
(c_float)-0.01000000000000000021,
};
static csc linsys_solver_KKT = {44, 14, 14, linsys_solver_KKT_p, linsys_solver_KKT_i, linsys_solver_KKT_x, -1};
static c_int linsys_solver_PtoKKT[6] = {
2,
7,
16,
4,
9,
18,
};
static c_int linsys_solver_AtoKKT[30] = {
3,
39,
11,
25,
32,
8,
20,
12,
26,
33,
17,
21,
40,
27,
34,
5,
41,
13,
28,
35,
10,
22,
14,
29,
36,
19,
23,
42,
30,
37,
};
static c_int linsys_solver_rhotoKKT[8] = {
1,
6,
0,
24,
43,
15,
31,
38,
};
static QDLDL_float linsys_solver_D[14] = {
0,
0,
101,
1,
0,
101,
1,
-1,
101,
1,
0,
-10,
-10,
0,
};
static QDLDL_int linsys_solver_etree[14] = {
8,
2,
3,
7,
5,
6,
7,
10,
9,
10,
11,
12,
13,
-1,
};
static QDLDL_int linsys_solver_Lnz[14] = {
2,
2,
5,
4,
2,
5,
4,
4,
5,
4,
3,
2,
1,
0,
};
static QDLDL_int   linsys_solver_iwork[42];
static QDLDL_bool  linsys_solver_bwork[14];
static QDLDL_float linsys_solver_fwork[14];
static qdldl_solver linsys_solver = {QDLDL_SOLVER, &solve_linsys_qdldl, &update_linsys_solver_matrices_qdldl, &update_linsys_solver_rho_vec_qdldl, &linsys_solver_L, linsys_solver_Dinv, linsys_solver_P, linsys_solver_bp, linsys_solver_sol, linsys_solver_rho_inv_vec, (c_float)0.00000100000000000000, 6, 8, linsys_solver_Pdiag_idx, 6, &linsys_solver_KKT, linsys_solver_PtoKKT, linsys_solver_AtoKKT, linsys_solver_rhotoKKT, linsys_solver_D, linsys_solver_etree, linsys_solver_Lnz, linsys_solver_iwork, linsys_solver_bwork, linsys_solver_fwork, };

// Define solution
static c_float xsolution[6];
static c_float ysolution[8];

static OSQPSolution solution = {xsolution, ysolution};

// Define info
static OSQPInfo info = {0, "Unsolved", OSQP_UNSOLVED, 0.0, 0.0, 0.0};

// Define workspace
static c_float work_rho_vec[8] = {
(c_float)100.00000000000000000000,
(c_float)100.00000000000000000000,
(c_float)100.00000000000000000000,
(c_float)100.00000000000000000000,
(c_float)100.00000000000000000000,
(c_float)100.00000000000000000000,
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
};
static c_float work_rho_inv_vec[8] = {
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
static c_int work_constr_type[8] = {
1,
1,
1,
1,
1,
1,
0,
0,
};
static c_float work_x[6];
static c_float work_y[8];
static c_float work_z[8];
static c_float work_xz_tilde[14];
static c_float work_x_prev[6];
static c_float work_z_prev[8];
static c_float work_Ax[8];
static c_float work_Px[6];
static c_float work_Aty[6];
static c_float work_delta_y[8];
static c_float work_Atdelta_y[6];
static c_float work_delta_x[6];
static c_float work_Pdelta_x[6];
static c_float work_Adelta_x[8];
static c_float work_D_temp[6];
static c_float work_D_temp_A[6];
static c_float work_E_temp[8];

OSQPWorkspace workspace_2uav_1hp_rod = {
&data, (LinSysSolver *)&linsys_solver,
work_rho_vec, work_rho_inv_vec,
work_constr_type,
work_x, work_y, work_z, work_xz_tilde,
work_x_prev, work_z_prev,
work_Ax, work_Px, work_Aty,
work_delta_y, work_Atdelta_y,
work_delta_x, work_Pdelta_x, work_Adelta_x,
work_D_temp, work_D_temp_A, work_E_temp,
&settings, &scaling, &solution, &info};

